language: android
sudo: required
jdk: openjdk8

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-29
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "platforms;android-29"

script:
- ./gradlew spotlessApply
- ./gradlew clean build --stacktrace

before_deploy:
- test -n "$KEYSTORE"
    && echo "$KEYSTORE" | base64 -d > $HOME/gotify-release-key.jks
    || true
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/gotify-release-key.jks
  -storepass android -keypass android app-release-unsigned.apk androiddebugkey
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/29.0.2/zipalign -v 4 app-release-unsigned.apk Gotify.apk"

deploy:
  provider: releases
  file: Gotify.apk
  api_key: $GH_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    # repo: gotify/android
    tags: true
    jdk: openjdk8
